trigger:
- main

pool:
  name: Azure Pipelines
variables:
  RestoreBuildProjects: '**/*.csproj'

steps:
- script: |
    echo "Current directory: $(Build.SourcesDirectory)"
    ls -R $(Build.SourcesDirectory)
  displayName: 'List directory contents'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x' # Set to a version suitable for your projects

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(TestProjects)' # Ensure this variable is also set properly
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
